---

- name: Create 'stack' group
  group: name=stack state=present
  become: yes

- name: Create 'stack' user
  user: name=stack group=stack state=present
  become: yes

- name: Create devstack directory
  file: path=/home/stack/devstack state=directory owner=stack group=stack
  become: yes

- name: Ensure users can sudo without password
  template:
    src: user-sudoers.j2
    dest: "/etc/sudoers.d/{{ item }}"
    owner: root
    group: root
    mode: 0440
  become: yes
  with_items: stack

- name: Clone devstack
  git: dest=/home/stack/devstack repo="https://github.com/openstack-dev/devstack"
  become: yes
  become_user: stack
