---

users:
  - jenkins
  - backdoor

dirs_to_create:
  - path: "~jenkins/bin"
    mode: "0755"
    owner: jenkins
    group: jenkins

files_to_copy:
  -  src: ironic-grenade.sh
     dest: "~jenkins/ironic-grenade.sh"
     mode: "0755"
     owner: jenkins
     group: jenkins
  -  src: update-projects.sh
     dest: "~jenkins/update-projects.sh"
     mode: "0644"
     owner: jenkins
     group: jenkins
  -  src: bash_aliases
     dest: "~jenkins/.bash_aliases"
     mode: "0644"
     owner: jenkins
     group: jenkins
  -  src: openrc
     dest: "~jenkins/openrc"
     mode: "0644"
     owner: jenkins
     group: jenkins
  -  src: remove-fluff.py
     dest: "~jenkins/bin/"
     mode: "0755"
     owner: jenkins
     group: jenkins
